default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-added-large-files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: ^\.zshrc$
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.6.1
    hooks:
      - id: betterleaks
      - id: betterleaks
        alias: betterleaks-working-tree
        name: Detect hardcoded secrets in working tree
        entry: betterleaks dir --redact --verbose .
        stages: [manual]
