# シェルの初期化処理
shell = "zsh"

# 必須プラグイン
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

# 便利ツール
[plugins.fzf]
github = "junegunn/fzf"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

# 補完機能
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# Git関連
[plugins.git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

# 追加の便利プラグイン
[plugins.colored-man-pages]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/colored-man-pages"

[plugins.extract]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/extract"

# 高度な設定例
[plugins.z]
github = "rupa/z"
apply = ["source"]

# 特定のファイルを読み込む場合
[plugins.custom-aliases]
inline = '''
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
'''
