# pkg管理
[[plugins]]
repo = 'Shougo/dein.vim'

# ColorScheme
[[plugins]]
repo = 'Mofiqul/vscode.nvim'
hook_add = '''
  let g:vscode_style = 'dark'
  colorscheme vscode
'''

# StatusLine追加
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_theme = 'minimalist'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  nmap <C-p> <Plug>AirlineSelectPrevTab
  nmap <C-n> <Plug>AirlineSelectNextTab
  '''

# StatusLineのColorTheme
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# coc nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
build = 'coc#util#install()'
hook_source = '''
  source ~/.config/nvim/settings/set_coc.vim
'''

# ファイラー
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
  '''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [figitive] <Nop>
    nnoremap <Leader>g [figitive]
    nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'sheerun/vim-polyglot'

# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'
