[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kannokanno/previm'
hook_source = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
'''
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
'''
on_ft = ['markdown']

[[plgins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
